// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://annkqgbavcggetkggqix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFubmtxZ2JhdmNnZ2V0a2dncWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNjg5NzMsImV4cCI6MjA2Mjk0NDk3M30.2aDDGvUGf2QpBGBXSsuMtnUbRIwRsq4zJmBV-zVXb0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);